sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: my--sky-itcast26125

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  wechat:
    appid: wx73e68f99fe429e5f
    secret: bf6676dc88a92c738eb3cbd85a91a4fb